apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260610-135113-fcp0iii5sg4y-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260610-135113-fcp0iii5sg4y.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260610-135113-fcp0iii5sg4y-service
            port:
              number: 80
