apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260610-135113-fcp0iii5sg4y-service
spec:
  selector:
    app: enterprise-system-20260610-135113-fcp0iii5sg4y
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
